# Generated by Django 3.1 on 2020-09-01 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200901_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user',
            name='permissao',
            field=models.IntegerField(blank=True, default=2),
        ),
        migrations.AlterField(
            model_name='custom_user',
            name='telefone',
            field=models.CharField(blank=True, default='1', max_length=50),
        ),
    ]
