# Generated by Django 3.1 on 2020-09-14 19:15

from django.db import migrations
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200901_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_user',
            name='local',
            field=mapbox_location_field.models.LocationField(default=(0, 0), map_attrs={}),
        ),
    ]
