# Generated by Django 3.1 on 2020-09-18 03:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200917_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_user',
            name='data_nascimento',
            field=models.DateField(default=datetime.date(2020, 9, 18)),
        ),
    ]
