# Generated by Django 3.1 on 2020-12-12 20:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_custom_user_data_nascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user',
            name='data_nascimento',
            field=models.DateField(default=datetime.date(2020, 12, 12)),
        ),
    ]
