# Generated by Django 3.1 on 2021-03-07 18:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20210217_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user',
            name='data_nascimento',
            field=models.DateField(default=datetime.datetime(2021, 3, 7, 18, 31, 39, 949925, tzinfo=utc)),
        ),
    ]
