# Generated by Django 3.1 on 2021-03-17 18:29

from django.db import migrations, models
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20210307_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='custom_user',
            name='local',
            field=mapbox_location_field.models.LocationField(default=(1.2, 1.2), map_attrs={'center': [17.031645, 51.106715], 'cursor_style': 'pointer', 'fullscreen_button': True, 'geocoder': True, 'marker_color': 'red', 'navigation_buttons': True, 'rotate': False, 'style': 'mapbox://styles/mapbox/outdoors-v11', 'track_location_button': True, 'zoom': 13}),
        ),
    ]
