# Generated by Django 3.1 on 2020-09-05 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_auto_20200903_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='motorista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Dia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('ativo', models.BooleanField(blank=True, default=True)),
                ('alunos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dia_alunos', to=settings.AUTH_USER_MODEL)),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dia_turmas', to='core.turma')),
            ],
        ),
    ]
