# Generated by Django 3.1 on 2020-09-05 22:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_auto_20200905_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dia',
            name='alunos',
        ),
        migrations.AddField(
            model_name='dia',
            name='alunos',
            field=models.ManyToManyField(related_name='dia_alunos', to=settings.AUTH_USER_MODEL),
        ),
    ]
