# Generated by Django 3.1 on 2020-09-06 00:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_auto_20200905_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dia',
            name='alunos',
            field=models.ManyToManyField(blank=True, related_name='dia_alunos', to=settings.AUTH_USER_MODEL),
        ),
    ]
