# Generated by Django 3.1 on 2020-09-07 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200907_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dia',
            name='alunos',
        ),
        migrations.AddField(
            model_name='aluno',
            name='dia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='aluno_dias', to='core.dia'),
        ),
    ]
