# Generated by Django 3.1 on 2020-09-08 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200907_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='esta_na_ida',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aluno',
            name='esta_na_volta',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='turma',
            name='vagas_restantes',
            field=models.IntegerField(default=10),
        ),
    ]
