# Generated by Django 3.1 on 2020-09-17 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200908_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turma',
            name='vagas',
        ),
        migrations.RemoveField(
            model_name='turma',
            name='vagas_restantes',
        ),
        migrations.AddField(
            model_name='turma',
            name='nome',
            field=models.CharField(default='', max_length=100),
        ),
    ]
