# Generated by Django 3.1 on 2020-09-18 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200917_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='menor_de_idade',
            field=models.BooleanField(default=False),
        ),
    ]
